# Generated by Django 4.1.3 on 2022-12-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_rename_img_movie_imqg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imqg',
            new_name='img',
        ),
    ]
